import { reactive, readonly } from 'vue';
import axios from 'axios';

// --- API Configuration ---
const API_BASE_URL = 'http://localhost:3000/api'; // Assuming backend runs on port 3000

const apiClient = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
});

// --- Type Definition for a Lego Set (ensure it matches frontend needs) ---
export interface LegoSet {
  id: number;
  name: string;
  setNumber: string;
  description?: string;
  pictures?: string[];
  numberOfPieces: number;
  numberOfMinifigs: number;
  quantityOwned: number;
  storageLocation?: string;
  isBuilt: boolean;
  status: 'Owned' | 'Wishlist' | 'Ordered';
}

// --- Reactive State ---
interface LegoStoreState {
  legoSets: LegoSet[];
  loading: boolean; // For UI feedback
  error: string | null; // For error messages
}

const state = reactive<LegoStoreState>({
  legoSets: [],
  loading: false,
  error: null,
});

// --- Store Methods ---

async function fetchAllSets() {
  state.loading = true;
  state.error = null;
  try {
    const response = await apiClient.get<LegoSet[]>('/legosets');
    state.legoSets = response.data;
  } catch (err: any) {
    state.error = err.response?.data?.message || err.message || 'Failed to fetch Lego sets.';
    console.error('Error fetching sets:', err);
    state.legoSets = []; // Clear sets on error or keep stale data?
  } finally {
    state.loading = false;
  }
}

// Call fetchAllSets once when the store is initialized (or app starts)
// This replaces loading from localStorage.
fetchAllSets();


function getAllSets(): Readonly<LegoSet[]> {
  // This now just returns the reactive state, which is populated by fetchAllSets etc.
  return readonly(state.legoSets);
}

type CreateLegoSetData = Omit<LegoSet, 'id'>; // ID is generated by backend

async function addSet(newSetData: CreateLegoSetData): Promise<LegoSet | null> {
  state.loading = true;
  state.error = null;
  try {
    const response = await apiClient.post<LegoSet>('/legosets', newSetData);
    // Add to local state or refetch? For simplicity, add to local state.
    // Or, backend could return the full list, or we could just call fetchAllSets().
    state.legoSets.push(response.data); // Optimistic update, or based on actual response
    return readonly(response.data);
  } catch (err: any) {
    state.error = err.response?.data?.message || err.response?.data?.error || err.message || 'Failed to add Lego set.';
    console.error('Error adding set:', err);
    return null;
  } finally {
    state.loading = false;
  }
}

function getSetById(id: number): Readonly<LegoSet> | undefined {
  // This can still find from local state if populated.
  // For a direct fetch if not found, an async version would be needed.
  const set = state.legoSets.find(s => s.id === id);
  return set ? readonly(set) : undefined;
}

// Async version if needed for direct fetch or ensuring latest data
async function fetchSetById(id: number): Promise<LegoSet | null> {
    state.loading = true;
    state.error = null;
    try {
        const response = await apiClient.get<LegoSet>(`/legosets/${id}`);
        // Optionally update local cache
        const index = state.legoSets.findIndex(s => s.id === id);
        if (index !== -1) {
            state.legoSets[index] = response.data;
        } else {
            // If not in cache, decide if you want to add it or if this function is purely for fetching
            // For now, let's assume it's for getting data, not necessarily populating the main list from here
        }
        return response.data;
    } catch (err: any) {
        state.error = err.response?.data?.message || err.message || 'Failed to fetch set by ID.';
        console.error(`Error fetching set ${id}:`, err);
        return null;
    } finally {
        state.loading = false;
    }
}


type UpdateLegoSetData = Partial<Omit<LegoSet, 'id'>>;

async function updateSet(id: number, updatedData: UpdateLegoSetData): Promise<LegoSet | null> {
  state.loading = true;
  state.error = null;
  try {
    // The backend PUT should return the updated set or success message.
    // Let's assume it returns the updated set object.
    const response = await apiClient.put<LegoSet | { message: string, id: number, changes: number }>(`/legosets/${id}`, updatedData);
    
    // If backend returns the full updated object
    if (response.data && typeof (response.data as LegoSet).name !== 'undefined') {
        const updatedSet = response.data as LegoSet;
        const setIndex = state.legoSets.findIndex(set => set.id === id);
        if (setIndex !== -1) {
          state.legoSets[setIndex] = { ...state.legoSets[setIndex], ...updatedSet };
        } else {
          // If not found, should it be added? Or error? Or refetch list?
          // This case implies data inconsistency or item was deleted. Refetch might be safest.
          fetchAllSets(); // Or handle error more specifically
        }
        return readonly(state.legoSets[setIndex]);
    } else if (response.data && (response.data as {message: string}).message) {
        // If backend returns a success message like { message: '...', id: ..., changes: ... }
        // We need to refetch the item or the whole list to get updated data
        const refreshedSet = await fetchSetById(id); // Fetch the updated item
         if (refreshedSet) return readonly(refreshedSet);
         return null; // Should not happen if update was successful
    }
    return null; // Fallback
  } catch (err: any) {
    state.error = err.response?.data?.message || err.response?.data?.error || err.message || 'Failed to update Lego set.';
    console.error('Error updating set:', err);
    return null;
  } finally {
    state.loading = false;
  }
}

async function deleteSet(id: number): Promise<boolean> {
  state.loading = true;
  state.error = null;
  try {
    await apiClient.delete(`/legosets/${id}`);
    const setIndex = state.legoSets.findIndex(set => set.id === id);
    if (setIndex !== -1) {
      state.legoSets.splice(setIndex, 1);
    }
    return true;
  } catch (err: any) {
    state.error = err.response?.data?.message || err.message || 'Failed to delete Lego set.';
    console.error('Error deleting set:', err);
    return false;
  } finally {
    state.loading = false;
  }
}

// Export the reactive state (as readonly for external use) and methods
export default {
  state: readonly(state),
  fetchAllSets, // Expose fetchAllSets if manual refresh is needed from components
  getAllSets,   // Returns current local state
  addSet,
  getSetById,   // Returns from local state
  fetchSetById, // Fetches specific item from API
  updateSet,
  deleteSet
};
